### ISSUE TITLE
Semantics of "id" for tasks unclear

### ISSUE THREAD

**Issue by FlorianDold** [docmalloc/gplmt#1]
Some elements in taskfiles have an "id".  Apparently the purpose of this id is to to
- identify tasks in debugging output, and
- select single sub-tasks for execution.

Some task-like elements, such as "sequence", "parallel" or "link" do not have an "id" according to tasklist_schema.xsd.  Is there any reason not to allow these elements to have an "id"?

It is also not clear whether the content of "id" must be unique, and what should happen if it is not unique.  Our answer to this should consider that we can also include tasks from other files, which may lead to clashes in the IDs.

**Comment by docmalloc** [comment]
id is to identify and to be able to refer to an element in a tasklist ... therefore 
- combined elements should also have ids
- ids should be unique

**Comment by FlorianDold** [comment]
Is there any reason to keep the IDs confined to integers?

**Comment by FlorianDold** [comment]
With the new experiment syntax, tasks are identified by their (namespaced) name.
