### ISSUE TITLE
Synchronization barriers should be implemented

### ISSUE THREAD

**Issue by FlorianDold** [docmalloc/gplmt#10]
Tasklists should have to ability to specify a synchronization barrier.  Execution of a tasklist only continues after a barrier if all (or a threshold of) nodes have reached the barrier.  

A barrier should be a new task element in the tasklist specification, e.g. `<barrier id="foo" />`.

It's not clear how barriers would interact with the `parallel` element.  If we don't find any good interpretation, we should disallow the `barrier` element in all but a top-level sequential task element.

Implementing this feature might entail some significant changes in the architecture of the worker queue.

**Comment by Egomania** [comment]
implementing the parallel element will fix the problem, in case every node is executing the same tasklist. tha fact that every node has to execute the same tasklist is a bit awkward in case you want to design huge experiment setups controlling nodes with different functionalities, in our case attacker and victims... so this may be a new issue and comes along with a mored detailed structures of tasks, taskslists and executors.

**Comment by FlorianDold** [comment]
Barriers are implemented with the `synchronize` element.
