### ISSUE TITLE
State/purpose of buildbot integration unclear

### ISSUE THREAD

**Issue by FlorianDold** [docmalloc/gplmt#12]
Some of the configuration variables refer to buildbot, but gplmt itself does not use buildbot anywhere. There's a script [1] that seems to do some mix of interfacing with planetlab and doing buildbot configuration.

We should clear up if and how we want to integrate GPLMT with buildbot.

[1] https://github.com/docmalloc/gplmt/blob/6eead57234250829dffdf50ba59ad22ea41c535c/scripts/gplmt-api.py

**Comment by docmalloc** [comment]
The buildbot integration is not required anymore ... before using zabbix, we had the idea to use buildbot as a experiment controlling software.

Feel free to remove the buildbot stuff.
