### ISSUE TITLE
XSD should be converted to a RELAX NG compact file.

### ISSUE THREAD

**Issue by FlorianDold** [docmalloc/gplmt#2]
XML Schema definitions are hardly human readable.  A better alternative would be to specify the schema for task lists in the RELAX NG compact specification language.

The rest of the project would not be affected, since tools like `trang` can convert the RELAX NG specifications back to XML Schema, unless some specific RELAX-NG-only features are used.

**Comment by FlorianDold** [comment]
Looks like this: https://github.com/docmalloc/gplmt/blob/py3-refactoring/contrib/tasklist_schema.rnc

Could use some comments, but we should get the details / semantics of task list right before.

**Comment by docmalloc** [comment]
Sounds reasonable to me... Waiting for Nadine to ACK

**Comment by Egomania** [comment]
ACK

**Comment by FlorianDold** [comment]
Done.
