### ISSUE TITLE
Node specification for tasks unclear

### ISSUE THREAD

**Issue by FlorianDold** [docmalloc/gplmt#3]
Some task-like elements (such as sequence, run, parallel) can be given zero or more "node" elements, which is a string.  This is not used anywhere in the code, except the following snippet,

``` python
if (task.node and task.node != self.node.hostname):
    g_logger.log (self.node.hostname + " : Ignoring task due to set node attribute");
    task = self.tasks.get()
    continue
```

where it is clearly ignored.

**Comment by docmalloc** [comment]
Can be removed due to experiment discussion
