### ISSUE TITLE
Code should be ported to Python3

### ISSUE THREAD

**Issue by FlorianDold** [docmalloc/gplmt#5]
Python3 has better support for asynchronous IO, which may be helpful when implementing more complex task list features.

Other Python3-only features such as enums fit nicely into the existing code base as well.

All libraries we use (except minixsv, which we replace with lxml) are already Python3-compatible.

The effort to port the existing code base to Python3 should be minimal, compared with the refactoring work that is required anyway.

**Comment by docmalloc** [comment]
ACK

**Comment by Egomania** [comment]
ACK

**Comment by FlorianDold** [comment]
gplmt-light is written in python3
