### ISSUE TITLE
User guide should be written in Sphinx

### ISSUE THREAD

**Issue by FlorianDold** [docmalloc/gplmt#7]
Sphinx (http://sphinx-doc.org/) seems appropriate for both the user guide and the code documentation.
- We don't seem to have the tex sources for the current user guide
- Sphinx can be converted to both tex and html / other formats
- It's much easier to edit Sphinx / reStructuredText

**Comment by Egomania** [comment]
you may show us an example of the promoted "beautiful documentation" [1]

[1] http://sphinx-doc.org/

**Comment by docmalloc** [comment]
Have a look:
http://sphinx-doc.org/examples.html

**Comment by FlorianDold** [comment]
Documentation is work in progress, and available at http://gplmt.readthedocs.org/en/latest/
