### ISSUE TITLE
Setting gplmt_parallelism to '0' never runs anything

### ISSUE THREAD

**Issue by FlorianDold** [docmalloc/gplmt#9]
Setting gplmt_parallelism to '0' is explicitly handled in GPLMT (https://github.com/docmalloc/gplmt/blob/6eead57234250829dffdf50ba59ad22ea41c535c/gplmt/Worker.py#L758) but just results in no work being executed, ever.

The value for parallelism should probably fall back to '1' instead.

**Comment by Egomania** [comment]
we may should sit together and talk about the structure of tasks again, to meet all new requirements

**Comment by FlorianDold** [comment]
Obsolete with gplmt-light.
